"""29_10_2017_19_55

Revision ID: d64179d50f2b
Revises: 63a09b2535dd
Create Date: 2017-10-29 19:55:17.256845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd64179d50f2b'
down_revision = '63a09b2535dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_phone', ['phone'], unique=1)

    # ### end Alembic commands ###
